Replace Azure with Actions
wpilibsuite/WPILibInstaller-Avalonia pull request #12
Opened 2020-09-08 16:10 UTC by Daltz333

2020-09-08 16:44 UTC, AustinShalit requested changes

2020-09-08 16:44 UTC, AustinShalit commented on .github/workflows/ci.yml
> +            path: build\outputs\
```suggestion
            path: build/outputs/
```

2020-09-08 16:44 UTC, AustinShalit commented on .github/workflows/ci.yml
> +          uses: eskatos/gradle-command-action@v1
Just run gradle directly here... no need to use a separate action.

2020-09-08 16:44 UTC, AustinShalit commented on .github/workflows/ci.yml
> +            java-version: 11
Make sure to specify arch here if we need 32b java.

2020-09-08 16:44 UTC, AustinShalit commented on .github/workflows/ci.yml
> +
eol @ eof

2020-09-08 16:44 UTC, AustinShalit commented on .github/workflows/ci.yml
> +            name: ${{ matrix.artifact-name }}-installer
```suggestion
            name: ${{ matrix.artifact-name }}
```

2020-09-08 16:59 UTC, ThadHouse commented
Can you pass a wildcard for the dotnet version? I'm going to keep updating it. 

Also, I'm not fully in line with this one switching. This job fails a lot, and rerunning only the failed builds is basically the only way to actually get a full build.

2020-09-08 19:35 UTC, AustinShalit commented
Wildcard dotnet version support is pending this: https://github.com/actions/setup-dotnet/pull/110

2020-10-30 04:57 UTC, AustinShalit approved these changes

2020-10-31 04:14 UTC, merged