Add More Shortcuts
wpilibsuite/WPILibInstaller-Avalonia pull request #128
Opened 2020-12-06 04:57 UTC by Daltz333

2020-12-06 07:04 UTC, ThadHouse approved these changes

2020-12-06 07:11 UTC, sciencewhiz commented on WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
> +            shortcutData.DesktopShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "vscode", "Code.exe"), $"WPILib VS Code {frcYear}", $"FRC VS Code {frcYear}"));
Still have FRC?

2020-12-06 17:03 UTC, sciencewhiz requested changes
Start Menu Icons should be in the programs folder. ![image](https://user-images.githubusercontent.com/4885091/101286808-7eb53800-37a1-11eb-8d04-c48a8d39af3e.png)

I think it would also be more standard to install everything in to programs/WPILib 2021, rather then installing vscode at the top level and having a folder just for tools.

2020-12-06 17:12 UTC, sciencewhiz commented
It would be nice if RobotBuilder used the RobotBuilder Icon, rather then the generic WPILib Icon. https://github.com/wpilibsuite/RobotBuilder/blob/master/src/main/resources/icons/robotbuilder.png

2020-12-06 18:01 UTC, Daltz333 commented
I can do the program thing. But the robotbuilder icon is not trivial for me as it's not downloaded in the installer.

2020-12-06 18:27 UTC, ThadHouse commented
Make an issue for the icons and I can do it

2020-12-11 02:54 UTC, sciencewhiz commented
It should go into Programs\2021 WPILib not 2021 Programs\2021 WPILib, and vscode needs to go there too.

![image](https://user-images.githubusercontent.com/4885091/101855894-1bb4ff80-3b19-11eb-94c0-4216774dadea.png)

2020-12-11 06:56 UTC, sciencewhiz approved these changes

2020-12-11 08:32 UTC, merged