Set integrated terminal java home and path based on OS
wpilibsuite/WPILibInstaller-Avalonia pull request #143
Opened 2021-01-01 23:02 UTC by sciencewhiz

Fixes #44

2021-01-01 23:04 UTC, prateekma requested changes

2021-01-01 23:04 UTC, prateekma commented on WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
> +            } else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
Should be OSX.

2021-01-02 00:03 UTC, sciencewhiz commented
It works on windows and linux. On MacOS, the new java path gets appended to the end of the path, rather then the beginning as specified, so it still uses the system java.

2021-01-02 00:12 UTC, sciencewhiz commented
https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed

2021-01-02 01:31 UTC, sciencewhiz commented
Neither of those two workarounds seem to work on MacOS. I think it's still better with this fix then without (JAVA_HOME is set, and the FRC jdk is added to the path, albeit at the end, so that if there isn't a system java for some reason, it would use the FRC jdk.

2021-01-02 05:39 UTC, PeterJohnson approved these changes

2021-01-02 05:39 UTC, merged