Add Choreo
wpilibsuite/WPILibInstaller-Avalonia pull request #440
Opened 2024-10-11 04:11 UTC by spacey-sooty

Resolves https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/422

2024-10-11 14:26 UTC, Gold856 requested changes

2024-10-11 14:26 UTC, Gold856 commented on scripts/tools.gradle
> +    config << advantageScopeItem
Should be Choreo

2024-10-15 00:24 UTC, sciencewhiz commented
ChoreoLib Vendordep should also be downloaded and included like we do with the commands vendordep

2024-10-15 01:49 UTC, calcmogul commented
I assume that's done by adding more stuff to gradleriobase/build.gradle?

2024-10-15 01:56 UTC, spacey-sooty commented
waiting on Choreo release.

2024-10-15 02:04 UTC, sciencewhiz commented
> I assume that's done by adding more stuff to gradleriobase/build.gradle?

https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blob/62f0b56e1d962aa806357feae0cfa06afc703303/scripts/maven.gradle#L201-L206

https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blob/62f0b56e1d962aa806357feae0cfa06afc703303/scripts/maven.gradle#L229-L235

2024-10-15 02:06 UTC, jwbonner requested changes

2024-10-15 02:06 UTC, jwbonner commented on scripts/tools.gradle
> +
It looks like you're missing the scripts for launching Choreo. These lines add it to the tools menu but I believe that button would be nonfunctional.

2024-10-15 02:11 UTC, rzblue requested changes

2024-10-15 02:11 UTC, rzblue commented on gradleriobase/build.gradle
> +        wpilibnewcommands(getNativeDependencyTypeClass('WPISharedMavenDependency')) {
```suggestion
        choreolib(getNativeDependencyTypeClass('WPISharedMavenDependency')) {
```

2024-10-15 02:54 UTC, Gold856 requested changes

2024-10-15 02:54 UTC, Gold856 commented on files/Choreo.vbs
> +fullExeName = fso.BuildPath(advantageScopeFolder, "Choreo-v2025.0.0-beta-4-Windows-x86_64-setup.exe")
Choreo

2024-10-15 03:09 UTC, Gold856 requested changes

2024-10-15 03:09 UTC, Gold856 commented on files/Choreo.vbs
> +fullExeName = fso.BuildPath(advantageScopeFolder, "Choreo.exe")
Remove AdvantageScope reference

2024-10-15 04:06 UTC, sciencewhiz commented on gradleriobase/build.gradle
> +        url = uri("https://SleipnirGroup.githun.io/ChoreoLib/dep")
```suggestion
        url = uri("https://SleipnirGroup.github.io/ChoreoLib/dep")

```

2024-10-15 04:25 UTC, sciencewhiz commented on gradleriobase/build.gradle
> +            version = wpilibFoundVersion
This should be the choreo version, not the wpilib version. There must be more missing for cpp since this should have failed

2024-10-15 04:28 UTC, sciencewhiz commented on gradleriobase/build.gradle
> +            version = wpilibFoundVersion
Need a `wpi.cpp.deps.useLibrary`... down below like romi/xrp/newcommands

2024-10-15 05:10 UTC, spacey-sooty commented
tested this locally it works

2024-10-15 05:18 UTC, calcmogul approved these changes
The Linux installer properly installed the Choreo binaries, vendordep JSON, and maven artifacts on my machine.

2024-10-15 05:33 UTC, merged

2024-10-15 05:36 UTC, jwbonner commented
It looks like the launch scripts aren't copied to the installer archive, so the tools menu still doesn't work. That needs to be added to `tools.gradle`.