Install Elastic
wpilibsuite/WPILibInstaller-Avalonia pull request #456
Opened 2024-10-16 21:13 UTC by Gold872

Resolves #423

2024-10-17 00:39 UTC, Gold856 requested changes

2024-10-17 00:39 UTC, Gold856 commented on scripts/elastic.gradle
> +def fineNameMacArm = 'Elastic-WPILib-macOS.zip'
```suggestion
def fileNameMacArm = 'Elastic-WPILib-macOS.zip'
```

2024-10-18 06:22 UTC, spacey-sooty requested changes

2024-10-18 06:22 UTC, spacey-sooty commented on files/Elastic.sh
> +fi
```suggestion
if [ "$OS_NAME" = "Darwin" ]; then
    open "$ELASTIC_PATH/elastic_dashboard.app"
else
    exec "$ELASTIC_PATH/elastic_dashboard"
fi
```

2024-10-18 14:55 UTC, spacey-sooty requested changes

2024-10-18 14:55 UTC, spacey-sooty commented on WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
> +            shortcutData.DesktopShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"{frcYear} WPILib Tools/Elastic ${frcYear}", $"Elastic {frcYear}", ""));
```suggestion
            shortcutData.DesktopShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"{frcYear} WPILib Tools/Elastic ${frcYear}", $"Elastic (WPILib) {frcYear}", ""));

```

2024-10-18 14:55 UTC, spacey-sooty commented on WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
> +            shortcutData.StartMenuShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"Programs/{frcYear} WPILib Tools/Elastic ${frcYear}", $"Elastic {frcYear}
```suggestion
            shortcutData.StartMenuShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"Programs/{frcYear} WPILib Tools/Elastic (WPILib) ${frcYear}", $"Elastic (WPILib) {frcYear}", ""));

```

2024-10-19 03:19 UTC, calcmogul commented on WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
> +            shortcutData.DesktopShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"{frcYear} WPILib Tools/Elastic ${frcYear}", $"Elastic (WPILib) {frcYear}",
```suggestion
            shortcutData.DesktopShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"{frcYear} WPILib Tools/Elastic (WPILib) ${frcYear}", $"Elastic (WPILib) {frcYear}", ""));

```

2024-10-21 01:34 UTC, calcmogul approved these changes

2024-10-21 01:36 UTC, Gold856 requested changes

2024-10-21 01:36 UTC, Gold856 commented on WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
> +            shortcutData.StartMenuShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"Programs/{frcYear} WPILib Tools/Elastic (WPILib) ${frcYear}", $"Elastic
```suggestion
            shortcutData.StartMenuShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"Programs/{frcYear} WPILib Tools/Elastic (WPILib) {frcYear}", $"Elastic (WPILib) {frcYear}", ""));

```

2024-10-23 03:54 UTC, sciencewhiz commented on WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
> +            shortcutData.DesktopShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"{frcYear} WPILib Tools/Elastic (WPILib) ${frcYear}", $"Elastic (WPILib) {f
```suggestion
            shortcutData.DesktopShortcuts.Add(new ShortcutInfo(Path.Join(frcHomePath, "elastic", "elastic_dashboard.exe"), $"{frcYear} WPILib Tools/Elastic (WPILib) {frcYear}", $"Elastic (WPILib) {frcYear}", ""));

```

2024-11-12 05:00 UTC, sciencewhiz commented
Elastic fails to run on macArm, likely because it isn't notarized.

2024-11-12 05:40 UTC, sciencewhiz commented
I might have been chasing something else. After the installer is run, elastic isn't unzipped. When I manually unzip it, it runs. While I was troubleshooting, I downloaded Elastic direct from GitHub and after unzipping both the WPILib and the regular versions, they didn't run for me.

2024-11-14 04:59 UTC, sciencewhiz commented
To fix the extraction, it needs code in the tools updater similar to AdvantageScope

https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blob/0c7f6270c45eb09070e388b09c396092487bc273/apps/ToolsUpdater/src/main/java/Program.java#L98-L117
https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blob/0c7f6270c45eb09070e388b09c396092487bc273/apps/ToolsUpdater/src/main/java/Program.java#L132-L133

2024-11-14 16:56 UTC, Gold872 commented
I'm looking into implementing this extraction, and I noticed that the AdvantageScope file extension for macos is a `.tar.gz` but Elastic is a `.zip`

I'm not entirely familiar with development on MacOS, is the `tar.gz` format required for portable apps on mac? I don't have a way of testing this on my machine.

2024-11-14 17:32 UTC, sciencewhiz commented
I thought that it might be a problem, but the zip extracts and runs on my Mac, so I don't think it's necessary to change to .tar.gz, although that would be a more standard for Mac and Linux.

2024-11-14 17:34 UTC, Gold872 commented
When extracting it on macos, did you have to extract it twice? I noticed that there was a zip file in the zip file

2024-11-14 20:37 UTC, Gold872 commented
I just did some playing around with the CI, turns out it was putting the zip file within another zip file when uploading. There isn't an easy way to get around it besides manually extracting it before manually uploading it to the release. I'll copy the code that AdvantageScope has for extracting and use it for this. The changes won't work until the next release which should be somewhat soon.

2024-11-14 21:34 UTC, sciencewhiz commented
> When extracting it on macos, did you have to extract it twice?

I didn't look specifically. The gui extracted automatically, but may have handled the double zipping seamlessly. 

.tar.gz is standard for Mac and Linux.

2024-11-14 22:25 UTC, Gold856 commented
The double zip is actually needed to ensure the bundle contents stay unchanged. If you try to upload the raw .app bundle as a GitHub Actions artifact, it will actually change permissions (and possibly some other things), which will causes the integrity checks to fail (since the contents aren't exactly the same). AdvantageScope is packaged the same way for Mac, with a double archive, one of which gets stripped during the installer build process, and then the final extraction happening on the user's computer. Elastic could stay as a zip, as long as macOS has `unzip` or another tool to extract zip files.

2024-11-14 23:45 UTC, Gold872 commented
I see, that explains why the double zip is needed. I'll probably keep Elastic in the `tar.gz` format since it seems to have more options with extractions.

The second extraction will keep failing until the next release since it's trying to find a `tar.gz` file that doesn't exist yet

2024-11-15 16:20 UTC, sciencewhiz commented
> The changes won't work until the next release which should be somewhat soon.

How soon? WPILib is planning another beta release this weekend, and it would be very nice to get Elastic in.

2024-11-15 16:21 UTC, sciencewhiz commented
> This does raise the question though of how to sign this with the WPILib signature, since at some point during the build process it would have to be double extracted, and then zipped again. Not sure how this should be done without having it lose the signature.

Normal extraction and compression shouldn't mess with the signature. It's just the way that Gradle does it that does.

2024-11-16 19:35 UTC, Gold872 commented
@sciencewhiz the new update + build should fix the macos extraction, let me know if there are any issues with it besides notarization

2024-11-16 20:06 UTC, sciencewhiz commented
It's still double compressed, a tar.gz is inside the zip, so it doesn't get successfully extracted in the ToolsUpdater

2024-11-16 20:12 UTC, Gold872 commented
> It's still double compressed, a tar.gz is inside the zip, so it doesn't get successfully extracted in the ToolsUpdater

iirc isn't it supposed to be double compressed and it gets extracted twice during the installation?

2024-11-16 20:29 UTC, Gold872 commented
Looking at how advantagescope is structured with its wpilib mac release, I think I see what I was doing wrong, this should hopefully fix it

2024-11-16 21:22 UTC, sciencewhiz commented
It's no longer double compressed, but the tar.gz didn't get extracted

2024-11-16 21:28 UTC, Gold872 commented
That's odd, it should have the same logic as advantagescope where it gets extracted during installation

2024-11-16 21:29 UTC, sciencewhiz commented
It does extract on a fresh install. I think that's a problem unrelated to this PR that I've seen before

2024-11-16 21:31 UTC, sciencewhiz commented
Windows failure if fixed by #470

2024-11-16 21:31 UTC, sciencewhiz approved these changes

2024-11-18 18:42 UTC, merged